apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pz8plbe75-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pz8plbe75-python 
  name: pz8plbe75-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pz8plbe75-python 
