apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pz8plbe75-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:03eb23f19f819cb53e7aad88f3761ec8a3bd88f7@sha256:962edf61cd86809d9e9ff1e16713320c2c4419ddc729dc4e8d3f8b71b3c63926
          name: container-image
